import { StyleSheet } from 'react-native';

export const FormStyle = StyleSheet.create({
  content: {
    flex: 1,
    padding: 16,
    maxWidth: 600,
    width: '100%',
    justifyContent: 'center',
  },
  simpleInput: {
    flex: 1,
    padding: 14,
    height: 52,
    fontSize: 16,
    margin: 0,
    fontFamily: 'Montserrat_500Medium',
  },
  input: {
    padding: 14,
    borderRadius: 4,
    fontSize: 16,
    marginBottom: 4,
    borderWidth: 1,
    fontFamily: 'Montserrat_500Medium',
    borderColor: '#BFBFBF',
  },
  inputWithIcon: {
    height: 52,
    borderRadius: 4,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: '#BFBFBF',
  },
  inputIconRight: {
    position: 'absolute',
    right: 0,
    top: 0,
    padding: 14,
  },
  inputWithLabel: {
    padding: 14,
    height: 52,
    borderRadius: 3,
    marginBottom: 4,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#BFBFBF',
  },
  errorLabel: {
    color: 'red',
    textAlign: 'right',
    fontSize: 12,
    paddingBottom: 4,
    margin: 0,
  },
  errorLabelLarge: {
    color: 'red',
    flex: 1,
    padding: 32,
    textAlign: 'center',
    fontSize: 16,
    paddingBottom: 4,
    margin: 0,
  },
  label: {
    fontFamily: 'Montserrat_700Bold',
    textAlign: 'left',
    fontSize: 14,
    paddingBottom: 8,
    margin: 0,
  },
  button: {
    fontFamily: 'Montserrat_700Bold',
    margin: 8,
    marginTop: 16,
    fontSize: 16,
    backgroundColor: '#E5002C',
  },
  text: {
    textAlign: 'center',
    margin: 8,
  },
  buttonGreyWithIcon: {
    backgroundColor: '#F6F6F6',
    borderRadius: 100,
    padding: 8,
  },
});

export const DropdownStyle = StyleSheet.create({
  button: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    flexWrap: 'nowrap',
    justifyContent: 'flex-start',
    padding: 14,
    marginBottom: 4,
    borderRadius: 4,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#BFBFBF',
  },
  buttonText: {
    fontSize: 16,
    marginTop: 2,
    width: '100%',
    fontFamily: 'Montserrat_500Medium',
    flex: 3,
    textAlign: 'left',
  },
  icon: {
    marginRight: 10,
  },
  overlay: {
    width: '102%',
    height: '100%',
    borderBottomWidth: 1,
    borderBottomColor: '#BFBFBF',
  },
  item: {
    zIndex: 999,
    paddingVertical: 24,
    fontSize: 16,
    fontFamily: 'Montserrat_500Medium',
    borderTopColor: '#DDDDDD',
    borderTopWidth: 0.5,
  },
  itemDesktop: {
    zIndex: 999,
    paddingHorizontal: 12,
    paddingVertical: 24,
    fontSize: 16,
    fontFamily: 'Montserrat_500Medium',
    borderTopColor: '#DDDDDD',
    borderTopWidth: 0.5,
  },
  desktopList: {
    position: 'absolute',
    marginTop: 40,
    borderColor: '#DDDDDD',
    borderWidth: 1,
    marginLeft: -15,
    width: '100.2%',
    backgroundColor: 'white',
    zIndex: 99,
  },
});
